dataset:
  dataset_id: gt-csse/iNat24-vit-b-16
  splits: "train"
  directory: data/inquire_inat/emb
  export_images: false

embedding:
  model_id: openai/clip-vit-base-patch16
  batch_size: 64
  directory: data/inquire_inat/emb

containers:
  - image: "qdrant/qdrant:latest"
    name: "qdrant"
    hostname: "localhost"
    ports:
      6333: 6333
    healthcheck:
      test: "curl -s http://localhost:6333/healthz | grep -q 'healthz check passed' || exit 1"
      interval: 3 * 10**9
      timeout: 2 * 10**9
      retries: 3

vectordb:
  type: qdrant.hnsw
  params:
    url: localhost
    port: "6333"
    collection_name: benchmark
    index_type: hnsw
    metric: cosine
    m: 64
    ef: 32
    batch_size: 1000

search:
  topk: 10
  queries_file: benchmark/queries.txt

update:
  add_count: 50
  delete_count: 30
